const withMT = require('@material-tailwind/react/utils/withMT');

const sizings = {
  nano: '4px',
  micro: '8px',
  mini: '12px',
  base: '16px',
  large: '24px',
  huge: '32px',
  giant: '40px',
  '3x': '48px',
  '4x': '64px',
  '5x': '80px',
  massive: '120px',
  '10x': '160px',
  colossal: '200px',
  xl: '600px',
  xls: '700px',
  100: '100%',
  75: '75%',
  50: '50%',
  25: '25%',
  '1%': '1%',
  '2%': '2%',
  '3%': '3%',
  '4%': '4%',
  '5%': '5%',
  '6%': '6%',
  '7%': '7%',
  '8%': '8%',
  '9%': '9%',
  '10%': '10%',
  '11%': '11%',
  '12%': '12%',
  '13%': '13%',
  '14%': '14%',
  '15%': '15%',
  '16%': '16%',
  '17%': '17%',
  '18%': '18%',
  '19%': '19%',
  '20%': '20%',
  '21%': '21%',
  '22%': '22%',
  '23%': '23%',
  '24%': '24%',
  '25%': '25%',
  '26%': '26%',
  '27%': '27%',
  '28%': '28%',
  '29%': '29%',
  '30%': '30%',
  '31%': '31%',
  '32%': '32%',
  '33%': '33%',
  '34%': '34%',
  '35%': '35%',
  '36%': '36%',
  '37%': '37%',
  '38%': '38%',
  '39%': '39%',
  '40%': '40%',
  '41%': '41%',
  '42%': '42%',
  '43%': '43%',
  '44%': '44%',
  '45%': '45%',
  '46%': '46%',
  '47%': '47%',
  '48%': '48%',
  '49%': '49%',
  '50%': '50%',
  '51%': '51%',
  '52%': '52%',
  '53%': '53%',
  '54%': '54%',
  '55%': '55%',
  '56%': '56%',
  '57%': '57%',
  '58%': '58%',
  '59%': '59%',
  '60%': '60%',
  '61%': '61%',
  '62%': '62%',
  '63%': '63%',
  '64%': '64%',
  '65%': '65%',
  '66%': '66%',
  '67%': '67%',
  '68%': '68%',
  '69%': '69%',
  '70%': '70%',
  '71%': '71%',
  '72%': '72%',
  '73%': '73%',
  '74%': '74%',
  '75%': '75%',
  '76%': '76%',
  '77%': '77%',
  '78%': '78%',
  '79%': '79%',
  '80%': '80%',
  '81%': '81%',
  '82%': '82%',
  '83%': '83%',
  '84%': '84%',
  '85%': '85%',
  '86%': '86%',
  '87%': '87%',
  '88%': '88%',
  '89%': '89%',
  '90%': '90%',
  '91%': '91%',
  '92%': '92%',
  '93%': '93%',
  '94%': '94%',
  '95%': '95%',
  '96%': '96%',
  '97%': '97%',
  '98%': '98%',
  '99%': '99%',
  '100%': '100%',
};

const colors = {
  primary: {
    primary: 'var(--primary)',
    'on-primary': 'var(--on-primary)',
    container: 'var(--primary-container)',
    'on-primary-container': 'var(--on-primary-container)',
  },
  secondary: {
    DEFAULT: 'var(--secondary)',
    secondary: 'var(--secondary)',
    'on-secondary': 'var(--on-secondary)',
    container: 'var(--secondary-container)',
    'on-secondary-container': 'var(--on-secondary-container)',
  },
  tertiary: {
    DEFAULT: 'var(--tertiary)',
    'on-tertiary': 'var(--on-tertiary)',
    container: 'var(--tertiary-container)',
    'on-tertiary-container': 'var(--on-tertiary-container)',
  },
  premium: {
    DEFAULT: 'var(--premium)',
    'on-premium': 'var(--on-premium)',
    container: 'var(--premium-container)',
    'on-premium-container': 'var(--on-premium-container)',
    20: 'var(--premium-20)',
    90: 'var(--premium-90)',
  },
  success: {
    success: 'var(--success)',
    'on-success': 'var(--on-success)',
    container: 'var(--success-container)',
    'on-success-container': 'var(--on-success-container)',
  },
  warning: {
    DEFAULT: 'var(--warning)',
    'on-warning': 'var(--on-warning)',
    container: 'var(--warning-container)',
    'on-warning-container': 'var(--on-warning-container)',
    40: 'var(--warning-40)',
    98: 'var(--warning-98)',
  },
  error: {
    DEFAULT: 'var(--error)',
    'on-error': 'var(--on-error)',
    container: 'var(--error-container)',
    'on-error-container': 'var(--on-error-container)',
  },
  surface: {
    DEFAULT: 'var(--surface)',
    'on-surface': 'var(--on-surface)',
    'surface-container': 'var(--surface-container)',
    'surface-container-lowest': 'var(--surface-container-lowest)',
    'surface-container-highest': 'var(--surface-container-highest)',
    'surface-bright': 'var(--surface-bright)',
    'surface-dim': 'var(--surface-dim)',
    'surface-variant': 'var(--surface-variant)',
    'on-surface-variant': 'var(--on-surface-variant)',
  },
  ui: {
    outline: {
      DEFAULT: 'var(--outline)',
      variant: 'var(--outline-variant)',
    },
  },
  default: {
    low: {
      DEFAULT: 'var(--low)',
      100: 'var(--low-100)',
      400: 'var(--low-400)',
      700: 'var(--low-700)',
    },
    high: {
      DEFAULT: 'var(--high)',
      100: 'var(--high-100)',
      400: 'var(--high-400)',
      700: 'var(--high-700)',
    },
    base: 'var(--base)',
  },
  neutral: {
    DEFAULT: 'var(--neutral)',
    'on-neutral': 'var(--on-neutral)',
    container: 'var(--neutral-container)',
    'on-neutral-container': 'var(--on-neutral-container)',
    low: {
      DEFAULT: 'var(--neutral-low)',
      100: 'var(--neutral-low-100)',
      200: 'var(--neutral-low-200)',
      300: 'var(--neutral-low-300)',
      400: 'var(--neutral-low-400)',
      500: 'var(--neutral-low-500)',
      550: 'var(--neutral-low-550)',
      600: 'var(--neutral-low-600)',
      700: 'var(--neutral-low-700)',
      800: 'var(--neutral-low-800)',
      900: 'var(--neutral-low-900)',
    },
    high: {
      DEFAULT: 'var(--neutral-high)',
      100: 'var(--neutral-high-100)',
      200: 'var(--neutral-high-200)',
      300: 'var(--neutral-high-300)',
      400: 'var(--neutral-high-400)',
      500: 'var(--neutral-high-500)',
      600: 'var(--neutral-high-600)',
    },
  },
  brand: {
    primary: {
      DEFAULT: 'var(--primary)',
      50: 'var(--primary-50)',
      100: 'var(--primary-100)',
      200: 'var(--primary-200)',
      300: 'var(--primary-300)',
      400: 'var(--primary-400)',
      500: 'var(--primary-500)',
      600: 'var(--primary-600)',
      700: 'var(--primary-700)',
      800: 'var(--primary-800)',
      850: 'var(--primary-850)',
      900: 'var(--primary-900)',
      950: 'var(--primary-950)',
      opacity: {
        light: 'var(--primary-opacity-light)',
      },
    },
    secondary: {
      DEFAULT: 'var(--secondary)',
      50: 'var(--secondary-50)',
      100: 'var(--secondary-100)',
      200: 'var(--secondary-200)',
      300: 'var(--secondary-300)',
      400: 'var(--secondary-400)',
      500: 'var(--secondary-500)',
      600: 'var(--secondary-600)',
      700: 'var(--secondary-700)',
      800: 'var(--secondary-800)',
    },
    tertiary: {
      DEFAULT: 'var(--tertiary)',
      50: 'var(--tertiary-50)',
      100: 'var(--tertiary-100)',
      200: 'var(--tertiary-200)',
      300: 'var(--tertiary-300)',
      400: 'var(--tertiary-400)',
      500: 'var(--tertiary-500)',
      600: 'var(--tertiary-600)',
      700: 'var(--tertiary-700)',
      800: 'var(--tertiary-800)',
    },
    premium: {
      DEFAULT: 'var(--premium)',
      50: 'var(--premium-50)',
      100: 'var(--premium-100)',
      200: 'var(--premium-200)',
      300: 'var(--premium-300)',
      400: 'var(--premium-400)',
      500: 'var(--premium-500)',
      600: 'var(--premium-600)',
      700: 'var(--premium-700)',
      900: 'var(--premium-900)',
    },
    highlight: {
      DEFAULT: 'var(--highlight)',
      50: 'var(--highlight-50)',
      100: 'var(--highlight-100)',
      200: 'var(--highlight-200)',
      300: 'var(--highlight-300)',
      400: 'var(--highlight-400)',
      500: 'var(--highlight-500)',
      600: 'var(--highlight-600)',
      700: 'var(--highlight-700)',
      800: 'var(--highlight-800)',
      900: 'var(--highlight-900)',
    },
  },
  feedback: {
    alert: {
      DEFAULT: 'var(--alert)',
      50: 'var(--alert-50)',
      100: 'var(--alert-100)',
      200: 'var(--alert-200)',
      300: 'var(--alert-300)',
      400: 'var(--alert-400)',
      500: 'var(--alert-500)',
      600: 'var(--alert-600)',
      700: 'var(--alert-700)',
      800: 'var(--alert-800)',
      900: 'var(--alert-900)',
      950: 'var(--alert-950)',
    },
    success: {
      DEFAULT: 'var(--success)',
      50: 'var(--success-50)',
      100: 'var(--success-100)',
      200: 'var(--success-200)',
      300: 'var(--success-300)',
      400: 'var(--success-400)',
      500: 'var(--success-500)',
      600: 'var(--success-600)',
      700: 'var(--success-700)',
      800: 'var(--success-800)',
      900: 'var(--success-900)',
      950: 'var(--success-950)',
    },
  },
  gradient: {
    secondary: {
      1: {
        from: 'var(--gradient-secondary-1-from)',
        via: 'var(--gradient-secondary-1-via)',
        to: 'var(--gradient-secondary-1-to)',
      },
      2: {
        from: 'var(--gradient-secondary-2-from)',
        to: 'var(--gradient-secondary-2-to)',
        via: 'var(--gradient-secondary-2-via)',
      },
    },
    primary: {
      1: {
        from: 'var(--gradient-primary-1-from)',
        via: 'var(--gradient-primary-1-via)',
        to: 'var(--gradient-primary-1-to)',
      },
      2: {
        from: 'var(--gradient-primary-2-from)',
        to: 'var(--gradient-primary-2-to)',
      },
    },
    premium: {
      1: {
        from: 'var(--gradient-premium-1-from)',
        via: 'var(--gradient-premium-1-via)',
        to: 'var(--gradient-premium-1-to)',
      },
      2: {
        from: 'var(--gradient-premium-2-from)',
        to: 'var(--gradient-premium-2-to)',
      },
      3: {
        from: 'var(--gradient-premium-3-from)',
        to: 'var(--gradient-premium-3-to)',
      },
    },
    neutral: {
      high: {
        1: {
          from: 'var(--gradient-neutral-high-1-from)',
          to: 'var(--gradient-neutral-high-1-to)',
        },
        2: {
          from: 'var(--gradient-neutral-high-2-from)',
          to: 'var(--gradient-neutral-high-2-to)',
        },
      },
      low: {
        1: {
          from: 'var(--gradient-neutral-low-1-from)',
          to: 'var(--gradient-neutral-low-1-to)',
        },
        2: {
          from: 'var(--gradient-neutral-low-2-from)',
          to: 'var(--gradient-neutral-low-2-to)',
        },
      },
    },
    feedback: {
      alert: {
        1: {
          from: 'var(--gradient-feedback-alert-1-from)',
          via: 'var(--gradient-feedback-alert-1-via)',
          to: 'var(--gradient-feedback-alert-1-to)',
        },
        2: {
          from: 'var(--gradient-feedback-alert-2-from)',
          to: 'var(--gradient-feedback-alert-2-to)',
        },
      },
      success: {
        1: {
          from: 'var(--gradient-success-1-from)',
          via: 'var(--gradient-success-1-via)',
          to: 'var(--gradient-success-1-to)',
        },
        2: {
          from: 'var(--gradient-success-2-from)',
          via: 'var(--gradient-success-2-via)',
          to: 'var(--gradient-success-2-to)',
        },
      },
    },
    highlight: {
      1: {
        from: 'var(--gradient-highlight-1-from)',
        via: 'var(--gradient-highlight-1-via)',
        to: 'var(--gradient-highlight-1-to)',
      },
      2: {
        from: 'var(--gradient-highlight-2-from)',
        via: 'var(--gradient-highlight-2-via)',
        to: 'var(--gradient-highlight-2-to)',
      },
    },
    DEFAULT: {
      from: 'var(--gradient-from)',
      via: 'var(--gradient-via)',
      to: 'var(--gradient-to)',
    },
  },
};

const fontFamily = {
  base: ['Roboto', 'sans-serif'],
  black: ['Roboto-Black', 'sans-serif'],
  bold: ['Roboto-Bold', 'sans-serif'],
  regular: ['Roboto-Regular', 'sans-serif'],
  light: ['Roboto-Light', 'sans-serif'],
  DEFAULT: ['Roboto', 'sans-serif'],
};

module.exports = withMT({
  mode: 'jit',
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './index.html',
    './node_modules/teste-embracon-components/**/*.{js,jsx,ts,tsx}',
    './node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}',
    './node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}',
    './node_modules/tw-elements-react/dist/js/**/*.js',
  ],
  plugins: [require('tw-elements-react/dist/plugin.cjs')],
  theme: {
    extend: {
      minWidth: {
        base: '600px',
      },
      spacing: sizings,
      brightness: {
        heavy: '0.9',
        medium: '1.2',
        light: '1.8',
      },
      backgroundImage: {
        'charts-line': "url('/src/images/charts/line.png')",
        'sum-icon': "url('/src/images/yearbox/sum.svg')",
        'subtraction-icon': "url('/src/images/yearbox/subtraction.svg')",
      },
    },
    colors: {
      ...colors,
      sys: colors,
    },
    fontFamily,
    fontWeight: {},
    fontSize: {
      'display-large-light': [
        '5rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 200,
        },
      ],
      'display-large': [
        '5rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 300,
        },
      ],
      'display-large-bold': [
        '5rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 400,
        },
      ],
      'display-large-black': [
        '5rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 900,
        },
      ],
      'display-medium-light': [
        '4rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 200,
        },
      ],
      'display-medium': [
        '4rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 300,
        },
      ],
      'display-medium-bold': [
        '4rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 400,
        },
      ],
      'display-medium-black': [
        '4rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 900,
        },
      ],
      'display-small-light': [
        '3rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 200,
        },
      ],
      'display-small': [
        '3rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 300,
        },
      ],
      'display-small-bold': [
        '3rem',
        {
          lineHeight: 1.2,
          letterSpacing: '-2.5%',
          fontWeight: 400,
        },
      ],
      'heading-xlarge-light': [
        '2rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 200,
        },
      ],
      'heading-xlarge': [
        '2rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 300,
        },
      ],
      'heading-xlarge-bold': [
        '2rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-xlarge-black': [
        '2rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 900,
        },
      ],
      'heading-large-light': [
        '1.75rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 200,
        },
      ],
      'heading-large': [
        '1.75rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 300,
        },
      ],
      'heading-large-bold': [
        '1.75rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-large-black': [
        '1.75rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 900,
        },
      ],
      'heading-medium-light': [
        '1.5rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 200,
        },
      ],
      'heading-medium': [
        '1.5rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-medium-bold': [
        '1.5rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-medium-black': [
        '1.5rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 900,
        },
      ],
      'heading-small-light': [
        '1.25rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 200,
        },
      ],
      'heading-small': [
        '1.25rem',
        {
          lineHeight: 1.625,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-small-bold': [
        '1.25rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 400,
        },
      ],
      'heading-small-black': [
        '1.25rem',
        {
          lineHeight: 1.3,
          letterSpacing: '-2%',
          fontWeight: 900,
        },
      ],
      'body-large-light': [
        '1.125rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 200,
        },
      ],
      'body-large': [
        '1.125rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 300,
        },
      ],
      'body-large-bold': [
        '1.125rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 400,
        },
      ],
      'body-large-black': [
        '1.125rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 900,
        },
      ],
      'body-medium-light': [
        '1rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 200,
        },
      ],
      'body-medium': [
        '1rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 400,
        },
      ],
      'body-medium-bold': [
        '1rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 700,
        },
      ],
      'body-medium-black': [
        '1rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 900,
        },
      ],
      'body-small-light': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 200,
        },
      ],
      'body-small': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 300,
        },
      ],
      'body-small-bold': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 400,
        },
      ],
      'body-small-black': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '0%',
          fontWeight: 900,
        },
      ],
      'label-large-light': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 200,
        },
      ],
      'label-large': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 300,
        },
      ],
      'label-large-bold': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 400,
        },
      ],
      'label-large-black': [
        '0.875rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 900,
        },
      ],
      'label-medium-light': [
        '0.75rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 200,
        },
      ],
      'label-medium': [
        '0.75rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 300,
        },
      ],
      'label-medium-bold': [
        '0.75rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 400,
        },
      ],
      'label-medium-black': [
        '0.75rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 900,
        },
      ],
      'label-small-light': [
        '0.625rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 200,
        },
      ],
      'label-small': [
        '0.625rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 300,
        },
      ],
      'label-small-bold': [
        '0.625rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 400,
        },
      ],
      'label-small-black': [
        '0.625rem',
        {
          lineHeight: 1.5,
          letterSpacing: '3%',
          fontWeight: 900,
        },
      ],
      mini: '0.5rem',
      xxs: '0.625rem',
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      lg: '1.25rem',
      xl: '1.5rem',
      xxl: '1.7rem',
      '2x': '2rem',
      '3x': '3rem',
      '4x': '4rem',
      '5x': '5rem',
    },
    letterSpacing: {
      display: '-2.5%',
      heading: '-2%',
      body: '0%',
      label: '3%',
      tight: '0rem',
      fit: '0.01rem',
      DEFAULT: '0.02rem',
      confortable: '0.03rem',
      distant: '0.05rem',
    },
    lineHeight: {
      compact: 1,
      display: 1.2,
      heading: 1.3,
      fit: 1.3,
      body: 1.5,
      label: 1.5,
      confortable: 1.6,
      distant: 1.8,
    },
    borderRadius: {
      sm: '0.25rem',
      md: '0.5rem',
      big: '0.75rem',
      lg: '1rem',
      xl: '2rem',
      full: '50%',
      60: '60px',
    },
    borderWidth: {
      DEFAULT: '1px',
      hairline: '1px',
      thin: '2px',
      thick: '4px',
      heavy: '8px',
    },
    opacity: {
      none: 0,
      heavy: 0.72,
      intense: 0.64,
      medium: 0.32,
      light: 0.16,
      transparent: 0.8,
      default: 1,
    },
    boxShadow: {
      'inner-1': 'var(--inner-1)',
      'inner-2': 'var(--inner-2)',
      'inner-3': 'var(--inner-3)',

      'drop-1': 'var(--drop-1)',
      'drop-2': 'var(--drop-2)',
      'drop-3': 'var(--drop-3)',

      'level-1': '0px 0px 1px 0 rgba(0, 0, 0, 0.04), 0px 0.75px 1.5px 0 rgba(0, 0, 0, 0.19)',
      'level-2': '0px 0.33px 1.5px 0 rgba(0, 0, 0, 0.04), 0px 1.25px 5px 0 rgba(0, 0, 0, 0.19)',
      'level-3': '0px 0.25px 3px 0 rgba(0, 0, 0, 0.04), 0px 2.75px 9px 0 rgba(0, 0, 0, 0.19)',
      'level-4': '0px 0.5px 5px 0 rgba(0, 0, 0, 0.04), 0px 3.75px 11px 0 rgba(0, 0, 0, 0.19)',
      'level-5': '0px 1px 6px 0 rgba(0, 0, 0, 0.04), 0px 5.5px 16px 0 rgba(0, 0, 0, 0.19)',

      'glow-primary-soft': 'var(--glow-primary-soft)',
      'glow-primary-medium': 'var(--glow-primary-medium)',
      'glow-primary-heavy': 'var(--glow-primary-heavy)',

      'glow-secondary-soft': 'var(--glow-secondary-soft)',
      'glow-secondary-medium': 'var(--glow-secondary-medium)',
      'glow-secondary-heavy': 'var(--glow-secondary-heavy)',

      'glow-tertiary-soft': 'var(--glow-tertiary-soft)',
      'glow-tertiary-medium': 'var(--glow-tertiary-medium)',
      'glow-tertiary-heavy': 'var(--glow-tertiary-heavy)',

      'glow-premium-soft': 'var(--glow-premium-soft)',
      'glow-premium-medium': 'var(--glow-premium-medium)',
      'glow-premium-heavy': 'var(--glow-premium-heavy)',

      'glow-highlight-soft': 'var(--glow-highlight-soft)',
      'glow-highlight-medium': 'var(--glow-highlight-medium)',
      'glow-highlight-heavy': 'var(--glow-highlight-heavy)',

      'glow-alert-soft': 'var(--glow-alert-soft)',
      'glow-alert-medium': 'var(--glow-alert-medium)',
      'glow-alert-heavy': 'var(--glow-alert-heavy)',

      'glow-success-soft': 'var(--glow-success-soft)',
      'glow-success-medium': 'var(--glow-success-medium)',
      'glow-success-heavy': 'var(--glow-success-heavy)',
    },
    dropShadow: {
      'inner-1': 'var(--inner-1)',
      'inner-2': 'var(--inner-2)',
      'inner-3': 'var(--inner-3)',

      'drop-1': 'var(--drop-1)',
      'drop-2': 'var(--drop-2)',
      'drop-3': 'var(--drop-3)',

      'level-1': '0px 0px 1px 0 rgba(0, 0, 0, 0.04), 0px 0.75px 1.5px 0 rgba(0, 0, 0, 0.19)',
      'level-2': '0px 0.33px 1.5px 0 rgba(0, 0, 0, 0.04), 0px 1.25px 5px 0 rgba(0, 0, 0, 0.19)',
      'level-3': '0px 0.25px 3px 0 rgba(0, 0, 0, 0.04), 0px 2.75px 9px 0 rgba(0, 0, 0, 0.19)',
      'level-4': '0px 0.5px 5px 0 rgba(0, 0, 0, 0.04), 0px 3.75px 11px 0 rgba(0, 0, 0, 0.19)',
      'level-5': '0px 1px 6px 0 rgba(0, 0, 0, 0.04), 0px 5.5px 16px 0 rgba(0, 0, 0, 0.19)',

      'glow-primary-soft': 'var(--glow-primary-soft)',
      'glow-primary-medium': 'var(--glow-primary-medium)',
      'glow-primary-heavy': 'var(--glow-primary-heavy)',

      'glow-secondary-soft': 'var(--glow-secondary-soft)',
      'glow-secondary-medium': 'var(--glow-secondary-medium)',
      'glow-secondary-heavy': 'var(--glow-secondary-heavy)',

      'glow-tertiary-soft': 'var(--glow-tertiary-soft)',
      'glow-tertiary-medium': 'var(--glow-tertiary-medium)',
      'glow-tertiary-heavy': 'var(--glow-tertiary-heavy)',

      'glow-premium-soft': 'var(--glow-premium-soft)',
      'glow-premium-medium': 'var(--glow-premium-medium)',
      'glow-premium-heavy': 'var(--glow-premium-heavy)',

      'glow-highlight-soft': 'var(--glow-highlight-soft)',
      'glow-highlight-medium': 'var(--glow-highlight-medium)',
      'glow-highlight-heavy': 'var(--glow-highlight-heavy)',

      'glow-alert-soft': 'var(--glow-alert-soft)',
      'glow-alert-medium': 'var(--glow-alert-medium)',
      'glow-alert-heavy': 'var(--glow-alert-heavy)',

      'glow-success-soft': 'var(--glow-success-soft)',
      'glow-success-medium': 'var(--glow-success-medium)',
      'glow-success-heavy': 'var(--glow-success-heavy)',
    },
  },
});
